from django.urls import path

from .views import (
    BakeryLoginView,
    BakeryLogoutView,
    CategoryCreateView,
    CategoryDeleteView,
    CategoryListView,
    CategoryUpdateView,
    DashboardView,
    IngredientCreateView,
    IngredientDeleteView,
    IngredientListView,
    IngredientUpdateView,
    InventoryDashboardView,
    InventoryLogListView,
    OrderCreateView,
    OrderDeleteView,
    OrderListView,
    OrderUpdateView,
    ProductCreateView,
    ProductDeleteView,
    ProductListView,
    ProductUpdateView,
    PurchaseCreateView,
    PurchaseDeleteView,
    PurchaseListView,
    PurchaseUpdateView,
    RecipeCreateView,
    RecipeDeleteView,
    RecipeListView,
    RecipeUpdateView,
    ReportsView,
    SaleListView,
    SupplierCreateView,
    SupplierDeleteView,
    SupplierListView,
    SupplierUpdateView,
    backup_database_view,
    pos_view,
    printable_receipt_pdf,
    restock_ingredient_view,
    restock_product_view,
    sale_receipt_view,
    sales_excel_export,
    sales_pdf_export,
)

urlpatterns = [
    path("login/", BakeryLoginView.as_view(), name="login"),
    path("logout/", BakeryLogoutView.as_view(), name="logout"),
    path("", DashboardView.as_view(), name="dashboard"),
    path("categories/", CategoryListView.as_view(), name="category-list"),
    path("categories/add/", CategoryCreateView.as_view(), name="category-add"),
    path("categories/<int:pk>/edit/", CategoryUpdateView.as_view(), name="category-edit"),
    path("categories/<int:pk>/delete/", CategoryDeleteView.as_view(), name="category-delete"),
    path("products/", ProductListView.as_view(), name="product-list"),
    path("products/add/", ProductCreateView.as_view(), name="product-add"),
    path("products/<int:pk>/edit/", ProductUpdateView.as_view(), name="product-edit"),
    path("products/<int:pk>/delete/", ProductDeleteView.as_view(), name="product-delete"),
    path("products/<int:pk>/restock/", restock_product_view, name="product-restock"),
    path("inventory/", InventoryDashboardView.as_view(), name="inventory-dashboard"),
    path("ingredients/", IngredientListView.as_view(), name="ingredient-list"),
    path("ingredients/add/", IngredientCreateView.as_view(), name="ingredient-add"),
    path("ingredients/<int:pk>/edit/", IngredientUpdateView.as_view(), name="ingredient-edit"),
    path("ingredients/<int:pk>/delete/", IngredientDeleteView.as_view(), name="ingredient-delete"),
    path("ingredients/<int:pk>/restock/", restock_ingredient_view, name="ingredient-restock"),
    path("recipes/", RecipeListView.as_view(), name="recipe-list"),
    path("recipes/add/", RecipeCreateView.as_view(), name="recipe-add"),
    path("recipes/<int:pk>/edit/", RecipeUpdateView.as_view(), name="recipe-edit"),
    path("recipes/<int:pk>/delete/", RecipeDeleteView.as_view(), name="recipe-delete"),
    path("suppliers/", SupplierListView.as_view(), name="supplier-list"),
    path("suppliers/add/", SupplierCreateView.as_view(), name="supplier-add"),
    path("suppliers/<int:pk>/edit/", SupplierUpdateView.as_view(), name="supplier-edit"),
    path("suppliers/<int:pk>/delete/", SupplierDeleteView.as_view(), name="supplier-delete"),
    path("purchases/", PurchaseListView.as_view(), name="purchase-list"),
    path("purchases/add/", PurchaseCreateView.as_view(), name="purchase-add"),
    path("purchases/<int:pk>/edit/", PurchaseUpdateView.as_view(), name="purchase-edit"),
    path("purchases/<int:pk>/delete/", PurchaseDeleteView.as_view(), name="purchase-delete"),
    path("orders/", OrderListView.as_view(), name="order-list"),
    path("orders/add/", OrderCreateView.as_view(), name="order-add"),
    path("orders/<int:pk>/edit/", OrderUpdateView.as_view(), name="order-edit"),
    path("orders/<int:pk>/delete/", OrderDeleteView.as_view(), name="order-delete"),
    path("sales/pos/", pos_view, name="pos"),
    path("sales/", SaleListView.as_view(), name="sale-list"),
    path("sales/<int:pk>/receipt/", sale_receipt_view, name="sale-receipt"),
    path("sales/<int:pk>/receipt.pdf", printable_receipt_pdf, name="sale-receipt-pdf"),
    path("inventory/logs/", InventoryLogListView.as_view(), name="inventory-logs"),
    path("reports/", ReportsView.as_view(), name="reports"),
    path("reports/sales.xlsx", sales_excel_export, name="sales-excel"),
    path("reports/sales.pdf", sales_pdf_export, name="sales-pdf"),
    path("backup/database/", backup_database_view, name="backup-database"),
]
