from django.urls import path

from .views import (
    ActivityLogListView,
    BakeryLoginView,
    BakeryLogoutView,
    BakeryPasswordResetCompleteView,
    BakeryPasswordResetConfirmView,
    BakeryPasswordResetDoneView,
    BakeryPasswordResetView,
    CategoryCreateView,
    CategoryDeleteView,
    CategoryListView,
    CategoryUpdateView,
    DashboardView,
    EmployeeCreateView,
    EmployeeDeleteView,
    EmployeeListView,
    EmployeePasswordResetView,
    EmployeeUpdateView,
    InventoryDashboardView,
    InventoryLogListView,
    LoginHistoryListView,
    OrderCreateView,
    OrderDeleteView,
    OrderListView,
    OrderUpdateView,
    ProductionBatchCreateView,
    ProductionBatchDeleteView,
    ProductionBatchListView,
    ProductionBatchUpdateView,
    ProductCreateView,
    ProductDeleteView,
    ProductListView,
    ProductUpdateView,
    ReportsView,
    SaleListView,
    SupplierCreateView,
    SupplierDeleteView,
    SupplierListView,
    SupplierUpdateView,
    archive_employee_view,
    archive_product_view,
    backup_database_view,
    pos_view,
    printable_receipt_pdf,
    restock_product_view,
    restore_database_view,
    sale_receipt_view,
    sales_csv_export,
    sales_excel_export,
    sales_pdf_export,
    void_sale_view,
)

urlpatterns = [
    path("login/", BakeryLoginView.as_view(), name="login"),
    path("logout/", BakeryLogoutView.as_view(), name="logout"),
    path("password-reset/", BakeryPasswordResetView.as_view(), name="password-reset"),
    path("password-reset/done/", BakeryPasswordResetDoneView.as_view(), name="password-reset-done"),
    path("password-reset/<uidb64>/<token>/", BakeryPasswordResetConfirmView.as_view(), name="password-reset-confirm"),
    path("password-reset/complete/", BakeryPasswordResetCompleteView.as_view(), name="password-reset-complete"),
    path("", DashboardView.as_view(), name="dashboard"),
    path("categories/", CategoryListView.as_view(), name="category-list"),
    path("categories/add/", CategoryCreateView.as_view(), name="category-add"),
    path("categories/<int:pk>/edit/", CategoryUpdateView.as_view(), name="category-edit"),
    path("categories/<int:pk>/delete/", CategoryDeleteView.as_view(), name="category-delete"),
    path("products/", ProductListView.as_view(), name="product-list"),
    path("products/add/", ProductCreateView.as_view(), name="product-add"),
    path("products/<int:pk>/edit/", ProductUpdateView.as_view(), name="product-edit"),
    path("products/<int:pk>/delete/", ProductDeleteView.as_view(), name="product-delete"),
    path("products/<int:pk>/archive/", archive_product_view, name="product-archive"),
    path("products/<int:pk>/restock/", restock_product_view, name="product-restock"),
    path("inventory/", InventoryDashboardView.as_view(), name="inventory-dashboard"),
    path("suppliers/", SupplierListView.as_view(), name="supplier-list"),
    path("suppliers/add/", SupplierCreateView.as_view(), name="supplier-add"),
    path("suppliers/<int:pk>/edit/", SupplierUpdateView.as_view(), name="supplier-edit"),
    path("suppliers/<int:pk>/delete/", SupplierDeleteView.as_view(), name="supplier-delete"),
    path("orders/", OrderListView.as_view(), name="order-list"),
    path("orders/add/", OrderCreateView.as_view(), name="order-add"),
    path("orders/<int:pk>/edit/", OrderUpdateView.as_view(), name="order-edit"),
    path("orders/<int:pk>/delete/", OrderDeleteView.as_view(), name="order-delete"),
    path("production/", ProductionBatchListView.as_view(), name="production-batch-list"),
    path("production/add/", ProductionBatchCreateView.as_view(), name="production-batch-add"),
    path("production/<int:pk>/edit/", ProductionBatchUpdateView.as_view(), name="production-batch-edit"),
    path("production/<int:pk>/delete/", ProductionBatchDeleteView.as_view(), name="production-batch-delete"),
    path("sales/pos/", pos_view, name="pos"),
    path("sales/", SaleListView.as_view(), name="sale-list"),
    path("sales/<int:pk>/receipt/", sale_receipt_view, name="sale-receipt"),
    path("sales/<int:pk>/void/", void_sale_view, name="sale-void"),
    path("sales/<int:pk>/receipt.pdf", printable_receipt_pdf, name="sale-receipt-pdf"),
    path("inventory/logs/", InventoryLogListView.as_view(), name="inventory-logs"),
    path("audit/activity/", ActivityLogListView.as_view(), name="activity-logs"),
    path("audit/logins/", LoginHistoryListView.as_view(), name="login-history"),
    path("employees/", EmployeeListView.as_view(), name="employee-list"),
    path("employees/add/", EmployeeCreateView.as_view(), name="employee-add"),
    path("employees/<int:pk>/edit/", EmployeeUpdateView.as_view(), name="employee-edit"),
    path("employees/<int:pk>/archive/", archive_employee_view, name="employee-archive"),
    path("employees/<int:pk>/delete/", EmployeeDeleteView.as_view(), name="employee-delete"),
    path("employees/<int:pk>/password/", EmployeePasswordResetView.as_view(), name="employee-password-reset"),
    path("reports/", ReportsView.as_view(), name="reports"),
    path("reports/sales.xlsx", sales_excel_export, name="sales-excel"),
    path("reports/sales.pdf", sales_pdf_export, name="sales-pdf"),
    path("reports/sales.csv", sales_csv_export, name="sales-csv"),
    path("backup/database/", backup_database_view, name="backup-database"),
    path("backup/restore/", restore_database_view, name="restore-database"),
]
