# Generated by Django 6.0.4 on 2026-05-01 19:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def backfill_purchase_units(apps, schema_editor):
    ingredient_purchase = apps.get_model('bakery', 'IngredientPurchase')
    for purchase in ingredient_purchase.objects.select_related('ingredient').filter(unit=''):
        purchase.unit = purchase.ingredient.unit
        purchase.save(update_fields=['unit'])


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='bakery.supplier'),
        ),
        migrations.AddField(
            model_name='ingredientpurchase',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredientpurchase',
            name='unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.RunPython(backfill_purchase_units, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ingredient',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity_in_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
