# Generated by Django 6.0.4 on 2026-05-24 14:59

from django.db import migrations, models


def remove_ingredient_inventory_logs(apps, schema_editor):
    inventory_log = apps.get_model("bakery", "InventoryLog")
    inventory_log.objects.filter(item_type="ingredient").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0006_remove_email_verification'),
    ]

    operations = [
        migrations.RunPython(remove_ingredient_inventory_logs, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredientpurchase',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredientpurchase',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='product',
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='action',
            field=models.CharField(choices=[('restock', 'Restock'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('void', 'Void')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='item_type',
            field=models.CharField(choices=[('product', 'Product')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='IngredientPurchase',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
